### ISSUE TITLE
Remove template override on uninstall

### ISSUE THREAD

**Issue by esedic** [alexandreelise/plg_system_coopacl#2]
After uninstalling plugin template override in administrator/templates/isis/html/com_users is not removed thus creating fatal error "0 Class 'CoopaclHelper' not found" on Users: Viewing Access Levels pages.

**Comment by alexandreelise** [comment]
Yes you are right. If you can add that please do. I don t much time to maintain my extension that s why i put them for free on github for developpers like you willing to enhance it for their projects. Take care.

**Comment by alexandreelise** [comment]
@esedic Thanks for your feedback both issues had been fixed.
